name: rust sccache
description: Shared Compilation Cache for Rust
inputs:
  version:
    description: The version of sccache to use
    required: true
    default: 'v0.3.1'
  key:
    description: An additional key for the cache
    required: false
  shared-key:
    description: An additional key that is stable over multiple jobs
    required: false
runs:
  using: composite
  steps:
    - id: rust
      name: Checking Rust version
      run: |
        version="$(rustc -vV)"
        echo "release=$(grep -oP 'release: \K.+' <<< "$version")" >> $GITHUB_OUTPUT
        echo "host=$(grep -oP 'host: \K.+' <<< "$version")" >> $GITHUB_OUTPUT
        echo "commit-hash=$(grep -oP 'commit-hash: \K.{0,12}' <<< "$version")" >> $GITHUB_OUTPUT
      shell: bash
    - id: platform
      name: Defining Platform to download
      env:
        OS: ${{ runner.os }}
      run: |
        platform='unknown-linux-musl'
        if [[ "$OS" == "macOS" ]]; then
          platform='apple-darwin'
        fi
        echo "platform=${platform}" >> $GITHUB_OUTPUT
      shell: bash
    - id: cache
      name: Computing cache key
      run: |
        key='v0-sccache'
        if [[ ! -z '${{ inputs.shared-key }}' ]]; then
          key="$key-${{ inputs.shared-key }}"
        else
          if [[ ! -z '${{ inputs.key }}' ]]; then
            key="$key-${{ inputs.key }}"
          fi
          key="$key-${{ github.job }}"
        fi
        key="$key-${{ steps.rust.outputs.release }}-${{ steps.rust.outputs.host }}-${{ steps.rust.outputs.commit-hash }}"
        hash='${{ hashFiles('**/Cargo.toml', '**/Cargo.lock', 'rust-toolchain', 'rust-toolchain.toml') }}'
        echo "key=$key-${hash:0:20}" >> $GITHUB_OUTPUT
        echo "restore-key=$key-" >> $GITHUB_OUTPUT
      shell: bash
    - name: Installing sccache
      run: |
        asset_name='sccache-${{ inputs.version }}-x86_64-${{ steps.platform.outputs.platform }}'
        curl --retry 5 --no-progress-meter --location --output "$asset_name.tar.gz" "https://github.com/mozilla/sccache/releases/download/${{ inputs.version }}/$asset_name.tar.gz"
        tar -zxf "$asset_name.tar.gz"
        cp "$asset_name/sccache" '/usr/local/bin/sccache'
        chmod +x '/usr/local/bin/sccache'
        rm -r "$asset_name"
        rm "$asset_name.tar.gz"
      shell: bash
    - name: Configuring sccache environment
      run: |
        if [ -z '${{ env.RUSTC_WRAPPER }}' ]; then
          echo 'RUSTC_WRAPPER=sccache' >> $GITHUB_ENV
        fi
        if [ -z '${{ env.SCCACHE_DIR }}' ]; then
          echo "SCCACHE_DIR=$(realpath ~/.cache/sccache)" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Deploying cache
      uses: env0/cache@64daede5552c68991cba51f3bc0ac2bc26945a11 # https://github.com/actions/cache/pull/489
      with:
        path: |
          ${{ env.SCCACHE_DIR }}
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          !target/**/bundle.car
        key: ${{ steps.cache.outputs.key }}
        restore-keys: |
          ${{ steps.cache.outputs.restore-key }}
